name: AWS ECR Build and Push

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:

permissions:
  contents: read 

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: 975050300138.dkr.ecr.us-east-1.amazonaws.com/opsbee-ecr-repo
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Authenticate with AWS using access keys
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      
      # Step 3: Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ env.ECR_REPOSITORY }}:latest 